apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
  - apiVersion: v1
    stringData:
      account: "account"
      password: "password"
      ldap-server: "server"
      ldap_port: "port"
    kind: Secret
    metadata:
      name: service-account-${ENV}
    type: Opaque
parameters:
  - description: Environment short name (dev,test,uat,prod)
    displayName: ENV
    name: ENV
    required: false
    value: "dev"
